# Generated by Django 4.1.7 on 2023-03-08 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
